ALTER TABLE employees RENAME COLUMN empolyee_id TO employee_id;
CREATE TABLE attendance (attendance_id INT PRIMARY KEY, employee_id INT, attendance_date DATE, status VARCHAR(20), FOREIGN KEY (employee_id) REFERENCES employees(employee_id));
INSERT INTO attendance VALUES (1, 1001, '2026-07-14', 'Present'), (2, 1002, '2026-07-14', 'Absent'), (3, 1004, '2026-07-14', 'Present');
SELECT * FROM attendance;
SELECT employees.employee_id, employees.employee_name, attendance.attendance_date, attendance.status FROM employees INNER JOIN attendance ON employees.employee_id = attendance.employee_id;
CREATE TABLE employee_leave (leave_id INT PRIMARY KEY, employee_id INT, leave_type VARCHAR(30), start_date DATE, end_date DATE, leave_status VARCHAR(20), FOREIGN KEY (employee_id) REFERENCES employees(employee_id));
INSERT INTO employee_leave VALUES (1, 1001, 'Casual Leave', '2026-07-20', '2026-07-21', 'Approved'), (2, 1002, 'Sick Leave', '2026-07-15', '2026-07-16', 'Approved'), (3, 1004, 'Personal Leave', '2026-07-25', '2026-07-25', 'Pending');
SELECT * FROM employee_leave;
SELECT employees.employee_id, employees.employee_name, employee_leave.leave_type, employee_leave.start_date, employee_leave.end_date, employee_leave.leave_status FROM employees INNER JOIN employee_leave ON employees.employee_id = employee_leave.employee_id;
CREATE TABLE projects (project_id INT PRIMARY KEY, project_name VARCHAR(100), employee_id INT, start_date DATE, end_date DATE, project_status VARCHAR(30), FOREIGN KEY (employee_id) REFERENCES employees(employee_id));
INSERT INTO projects VALUES (201, 'HR Management System', 1001, '2026-01-10', '2026-06-30', 'Completed'), (202, 'Banking Application', 1002, '2026-03-01', '2026-12-31', 'In Progress'), (203, 'Finance Dashboard', 1004, '2026-05-15', '2027-01-31', 'In Progress');
SELECT * FROM projects;
SELECT employees.employee_name, projects.project_name, projects.project_status FROM employees INNER JOIN projects ON employees.employee_id = projects.employee_id;
CREATE TABLE salary_history (salary_id INT PRIMARY KEY, employee_id INT, salary DECIMAL(10,2), effective_date DATE, FOREIGN KEY (employee_id) REFERENCES employees(employee_id));
INSERT INTO salary_history VALUES (1,1001,35000,'2026-01-01'),(2,1002,30000,'2026-01-01'),(3,1004,40000,'2026-01-01');
SELECT * FROM salary_history;
SELECT employees.employee_name, salary_history.salary, salary_history.effective_date FROM employees INNER JOIN salary_history ON employees.employee_id = salary_history.employee_id;
CREATE TABLE performance_review (review_id INT PRIMARY KEY, employee_id INT, review_date DATE, rating INT, manager_feedback VARCHAR(200), FOREIGN KEY (employee_id) REFERENCES employees(employee_id));
INSERT INTO performance_review VALUES (1,1001,'2026-06-30',5,'Excellent Performance'),(2,1002,'2026-06-30',4,'Good Performance'),(3,1004,'2026-06-30',5,'Outstanding Performance');
SELECT * FROM performance_review;
SELECT employees.employee_name, performance_review.rating, performance_review.manager_feedback FROM employees INNER JOIN performance_review ON employees.employee_id = performance_review.employee_id;
CREATE TABLE assets (asset_id INT PRIMARY KEY,employee_id INT,asset_name VARCHAR(50),asset_serial_no VARCHAR(50),issue_date DATE,asset_status VARCHAR(30),FOREIGN KEY (employee_id) REFERENCES employees(employee_id));
INSERT INTO assets VALUES (1,1001,'Laptop','LAP1001','2026-01-05','Issued'),(2,1002,'ID Card','ID1002','2026-01-05','Issued'),(3,1004,'Monitor','MON1004','2026-01-05','Issued');
SELECT * FROM assets;
SELECT employees.employee_name, assets.asset_name, assets.asset_serial_no, assets.asset_status FROM employees INNER JOIN assets ON employees.employee_id = assets.employee_id;